== configureInquiryAIHost()
`configureInquiryAIHost(hostname: str)`

DEPRECATED: Configure the hostname of the InquiryAI service.
[discrete]
==== Parameter:
* `hostname (str)`: The hostname (and port number) of the InquiryAI serivce.


== configureCoPilotHost()
`configureCoPilotHost(hostname: str)`

Configure the hostname of the CoPilot service.
[discrete]
==== Parameter:
* `hostname (str)`: The hostname (and port number) of the CoPilot serivce.


== registerCustomQuery()
`registerCustomQuery(function_header: str, description: str, docstring: str, param_types: dict)`

Register a custom query with the InquiryAI service.
[discrete]
==== Parameters:
* `function_header (str)`: The name of the query being registered.
* `description (str)`: The high-level description of the query being registered.
* `docstring (str)`: The docstring of the query being registered. Includes information about each parameter.
* `param_types (Dict[str, str])`: The types of the parameters. In the format {"param_name": "param_type"}
[discrete]
==== Returns:
Hash of query that was registered.


== updateCustomQuery()
`updateCustomQuery(function_header: str, description: str, docstring: str, param_types: dict)`

Update a custom query with the InquiryAI service.
[discrete]
==== Parameters:
* `function_header (str)`: The name of the query being updated.
* `description (str)`: The high-level description of the query being updated.
* `docstring (str)`: The docstring of the query being updated. Includes information about each parameter.
* `param_types (Dict[str, str])`: The types of the parameters. In the format {"param_name": "param_type"}
[discrete]
==== Returns:
Hash of query that was updated.


== deleteCustomQuery()
`deleteCustomQuery(function_header: str)`

Delete a custom query with the InquiryAI service.
[discrete]
==== Parameter:
* `function_header (str)`: The name of the query being deleted.
[discrete]
==== Returns:
Hash of query that was deleted.


== retrieveDocs()
`retrieveDocs(query: str, top_k: int = 3)`

Retrieve docs from the vector store.
[discrete]
==== Parameters:
* `query (str)`: The natural language query to retrieve docs with.
* `top_k (int)`: The number of docs to retrieve.
[discrete]
==== Returns:
List of docs retrieved.


== query()
`query(query)`

Query the database with natural language.
[discrete]
==== Parameter:
* `query (str)`: Natural language query to ask about the database.
[discrete]
==== Returns:
JSON including the natural language response, a answered_question flag, and answer sources.


== coPilotHealth()
`coPilotHealth()`

Check the health of the CoPilot service.
[discrete]
==== Returns:
JSON response from the CoPilot service.


== initializeSupportAI()
`initializeSupportAI()`

Initialize the SupportAI service.
[discrete]
==== Returns:
JSON response from the SupportAI service.


== createDocumentIngest()
`createDocumentIngest(data_source, data_source_config, loader_config, file_format)`

Create a document ingest.
[discrete]
==== Parameters:
* `data_source (str)`: The data source of the document ingest.
* `data_source_config (dict)`: The configuration of the data source.
* `loader_config (dict)`: The configuration of the loader.
* `file_format (str)`: The file format of the document ingest.
[discrete]
==== Returns:
JSON response that contains the load_job_id and data_source_id of the document ingest.


== runDocumentIngest()
`runDocumentIngest(load_job_id, data_source_id, data_path)`

Run a document ingest.
[discrete]
==== Parameters:
* `load_job_id (str)`: The load job ID of the document ingest.
* `data_source_id (str)`: The data source ID of the document ingest.
* `data_path (str)`: The data path of the document ingest.
[discrete]
==== Returns:
JSON response from the document ingest.


== searchDocuments()
`searchDocuments(query, method = "hnswoverlap", method_parameters: dict)`

Search documents.
[discrete]
==== Parameters:
* `query (str)`: The query to search documents with.
* `method (str)`: The method to search documents with.
* `method_parameters (dict)`: The parameters of the method.
[discrete]
==== Returns:
JSON response from the document search.


== answerQuestion()
`answerQuestion(query, method = "hnswoverlap", method_parameters: dict)`

Answer a question.
[discrete]
==== Parameters:
* `query (str)`: The query to answer the question with.
* `method (str)`: The method to answer the question with.
* `method_parameters (dict)`: The parameters of the method.
[discrete]
==== Returns:
JSON response from the question answer.


== forceConsistencyUpdate()
`forceConsistencyUpdate()`

Force a consistency update for SupportAI embeddings.
[discrete]
==== Returns:
JSON response from the consistency update.


